import * as Empty from "./emptyEntities";

export default {
  products: [],
  items: [
    Object.assign({}, Empty.ITEM, {itemId: 0}),
    Object.assign({}, Empty.ITEM, {itemId: 1}),
    Object.assign({}, Empty.ITEM, {itemId: 2}),
    Object.assign({}, Empty.ITEM, {itemId: 3}),
    Object.assign({}, Empty.ITEM, {itemId: 4}),
    Object.assign({}, Empty.ITEM, {itemId: 5}),
    Object.assign({}, Empty.ITEM, {itemId: 6}),
    Object.assign({}, Empty.ITEM, {itemId: 7}),
    Object.assign({}, Empty.ITEM, {itemId: 8}),
    Object.assign({}, Empty.ITEM, {itemId: 9}),
    Object.assign({}, Empty.ITEM, {itemId: 10}),
    Object.assign({}, Empty.ITEM, {itemId: 11}),
    Object.assign({}, Empty.ITEM, {itemId: 12}),
    Object.assign({}, Empty.ITEM, {itemId: 13}),
    Object.assign({}, Empty.ITEM, {itemId: 14}),
    Object.assign({}, Empty.ITEM, {itemId: 15}),
    Object.assign({}, Empty.ITEM, {itemId: 16}),
    Object.assign({}, Empty.ITEM, {itemId: 17}),
    Object.assign({}, Empty.ITEM, {itemId: 18}),
    Object.assign({}, Empty.ITEM, {itemId: 19}),
    Object.assign({}, Empty.ITEM, {itemId: 20}),
    Object.assign({}, Empty.ITEM, {itemId: 21}),
    Object.assign({}, Empty.ITEM, {itemId: 22}),
    Object.assign({}, Empty.ITEM, {itemId: 23}),
    Object.assign({}, Empty.ITEM, {itemId: 24}),
    Object.assign({}, Empty.ITEM, {itemId: 25}),
    Object.assign({}, Empty.ITEM, {itemId: 26}),
    Object.assign({}, Empty.ITEM, {itemId: 27}),
    Object.assign({}, Empty.ITEM, {itemId: 28}),
  ]
};
